### ISSUE TITLE
lbpcascade_animeface.xml not found?

### ISSUE THREAD

**Issue by Zusier** [nagadomi/lbpcascade_animeface#8]
Hi, sorry if I sound really stupid, but I'm getting this error when I run "python detect.py test.png"

Full response here
`Traceback (most recent call last):
  File "detect.py", line 30, in <module>
    detect(sys.argv[1])
  File "detect.py", line 7, in detect
    raise RuntimeError("%s: not found" % cascade_file)
RuntimeError: ../lbpcascade_animeface.xml: not found`

What do I do? I have the xml downloaded in the right place

**Comment by Zusier** [comment]
Oh, I didnt specify the destination of the xml :P
Now I have a new error: 
`Traceback (most recent call last):
  File "detect.py", line 30, in <module>
    detect(sys.argv[1])
  File "detect.py", line 11, in detect
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(3.4.9) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

honestly might just quit my project, have tried about 5 different face/head image croppers and extractors and nothing works.
